Exceptions Homework
olgayuks/QA-Lab-homeworks pull request #2
Opened 2021-02-28 13:31 UTC by olgayuks

2021-03-02 15:21 UTC, mashadolya requested changes
Code Conventions!!! 🙊

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Exceptions/PhoneUnavailableException.cs
> +    public class PhoneUnavailableException : Exception
а где три конструктора из бестр практис?)

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Models/Shop.cs
> +        public List<Phone> Phones { get; set; }
где пустые строки? 
Code Conventions!!!!

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Models/Shop.cs
> +        public int NumberOfAvailablePhones(OperationSystemType type)
Методы, которые что то возвращают, лучше назвать с `Get`...

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Models/Shop.cs
> +        public int NumberOfAvailablePhones(OperationSystemType type)
Модель должна только описывать какую-то сущность, подсчет количества телефонов стоит вынести в другой класс

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Models/OperationSystemType.cs
> +﻿namespace ExceptionsHomework.Models
для enum создаем в директории `Models `директорию `Enums`

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Menu/CatalogMenu.cs
> +            foreach (var shop in _phoneCatalog.GetShops())
Лучше объявить переменную перед `foreach ` для `_phoneCatalog.GetShops()`, таким образом мы вызовем данный метод один раз.
В твоем случае у тебя на каждой итерации происходит вызов метода `GetShops()`

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Menu/CatalogMenu.cs
> +            bool isSuccess = false;
Why don't `var `or `const`?

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Menu/CatalogMenu.cs
> +                    _log.Error("Введенный Вами товар не найден. Попробуйте выбрать другой товар.");
тут должно быть что то типа `log.Error(ex.Message)`

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Menu/CatalogMenu.cs
> +        public List<Phone> ChoosePhoneMenu()
Я бы назвала метод `GetPhonesByModel` или что то типа того.
Исходя из твоего названия не совсем понятно что за меню.
Методы стоит называть таким обращом, чтобы нам не приходилось вдаваться в подробности кода для того, чтобы понять, что делает данный метод.

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Menu/CatalogMenu.cs
> +            _log.Info($"В каком магазине Bы хотите приобрести {phones[0].Model} ?");
А чего мы тут берем `phones[0]`?

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Catalog/PhoneCatalog.cs
> +        private Dictionary<int, Shop> _shops;
зачем Dictionary?

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Catalog/PhoneCatalog.cs
> +            var isUnavailable = false;
isAvailable = true :)

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Catalog/PhoneCatalog.cs
> +            foreach (var phone in _phones)
ваще не понятно какие пхоны и где мы ищем и куда добавляем, приходится вчитываться в код, чтобы разобраться......
Naming changes requested

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Program.cs
> +            BasicConfigurator.Configure();
Это точно нужно?

2021-03-02 15:21 UTC, mashadolya commented on ExceptionsHomework/Program.cs
> +            }
Почему бы не создать отдельный класс для этой логики?

2021-03-02 17:13 UTC, olgayuks commented on ExceptionsHomework/Program.cs
> +            BasicConfigurator.Configure();
Требуется вызвать этот метод для конфигурации логгера.
https://logging.apache.org/log4net/release/manual/configuration.html

2021-03-02 17:19 UTC, olgayuks commented on ExceptionsHomework/Catalog/PhoneCatalog.cs
> +        private Dictionary<int, Shop> _shops;
Для выдачи информации о магазине для конкретного телефона. 
Пункт 3, когда успешно найдены телефоны, необходимо также выводить информацию о магазине. Быстрее это делать через dictionary
Пункт 4, когда ищем в каком магазине заказать телефон, так как телефонов с такой моделью может быть несколько, то для каждого телефона надо было бы пройтись по списку магазинов. dictionary в таком случае работает быстрее

2021-03-02 17:48 UTC, olgayuks commented on ExceptionsHomework/Menu/CatalogMenu.cs
> +            foreach (var shop in _phoneCatalog.GetShops())
не будет он каждый раз вызываться, я попробовала) но для читаемости кода исправлю)

2021-03-09 13:27 UTC, Maria-Dolia approved these changes

2021-03-09 13:27 UTC, Maria-Dolia commented on ExceptionsHomework/Catalog/PhoneCatalog.cs
> +            return _shops[id];
а что если id будет больше, чем количество шопов? Шопов 3, а й попрошу 4ый шоп

2021-03-09 13:27 UTC, Maria-Dolia commented on ExceptionsHomework/Catalog/PhoneCatalog.cs
> +namespace ExceptionsHomework.Catalog
CatalogS

2021-04-28 07:13 UTC, merged